apiVersion: v1
kind: Service
metadata:
  namespace: sqlrunner
  labels:
    app: sqlrunner-np
  name: sqlrunner-np
spec:
  ports:
    - name: sqlrunner-svc-ports
      port: 80
      targetPort: 8080
      nodePort: 32438
      protocol: TCP
  selector:
    app: sqlrunner
  type: NodePort
status:
  loadBalancer: {}