apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sqlrunner
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sqlrunner
spec:
  # image: registry.planet10.lab/apps/sqlrunner:1.0
  source:
    git:
      url: https://github.com/sdeeg-vmware/sqlrunner.git
      ref:
        branch: main