apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sqlrunner
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sqlrunner
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sdeeg-vmware/sqlrunner.git
      ref:
        branch: main