apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: sqlrunner
  namespace: builds
spec:
  tag: registry.planet10.lab/apps/sqlrunner
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: base
  serviceAccount: kpack-sa
  source:
    git:
      revision: master
      url: https://github.com/sdeeg-pivotal/sqlrunner.git
status: {}
